export const categories = [
  { id: "wireless-pc-headsets", name: "Headsets for PC's" },
  { id: "usb-pc-headsets", name: "Headsets for PC's" },
  { id: "yealink-headsets", name: "Headsets for Phone" },
  { id: "poly-handsets", name: "Headsets for Phone" },
  { id: "wireless-headsets", name: "Headsets by Type" },
  { id: "corded-qd-headsets", name: "Headsets by Type" },
];

export const productsByCategory = {
  "wireless-pc-headsets": [
    {
      id: 1,
      imageSrc: "https://www.headset-store.co.uk/user/products/Jabra%20Evolve%2065%20MS%20Stereo%20PC%20Headset-1.jpg",
      ProductName: "Jabra Evolve 65 SE MS Stereo Wireless PC & Bluetooth Headset",
      price: "61.05",
      description:
        "The Jabra Evolve 65 SE MS Stereo PC Headset is designed for use with PC and mobile phone/tablet applications. With state-of-the-art noise-cancelling technologies, the Jabra Evolve headset range is specially designed to improve conversation quality. Its noise-cancelling microphone eliminates annoying and distracting background sound, allowing you to be more focused on your calls. The E-STD standard microphone sensitivity is comparable to a normal telephone receiver, ensuring that no sound quality is lost by using a headset. Additionally, Wideband audio and Digital Signal Processing (DSP) technologies help to suppress echoes and clearly transmit your voice and music, to offer the highest quality experience, not only for softphone calls but also for music streaming.",
      features: [
        "Certified for Microsoft Teams",
        "Noise-cancelling technologies, wideband audio and DSP for conversation clarity",
        "Binaural version",
        "E-STD microphone sensitivity",
        "Bluetooth 4.0",
        "Range: up to 30m/100m",
        "NFC enabled for quick pairing",
        "Includes Jabra Link 380 USB Bluetooth adapter",
        "Multipoint technology for connecting two devices",
        "Large, leatherette ear cushions",
        "Soft carry pouch included",
        "In-call indicator lights",
        "Up to 10 hours talk time",
      ],
      packageContents: [
        "Jabra Evolve Bluetooth Headset",
        "Carry Pouch",
        "Jabra USB-A Wireless Bluetooth Adapter",
        "USB-A charging cable",
      ],
      additionalInformation: [
        { label: "Model", value: "21613" },
        { label: "Bar Code", value: "0017229160170" },
        { label: "Part Number", value: "209745-201" },
        { label: "Brand", value: "Jabra" },
        { label: "Corded or Cordless", value: "Cordless" },
        { label: "New or Refurbished?", value: "Brand New" },
        { label: "For Use With", value: "PC and mobile phone/tablet" },
        { label: "Connects Using", value: "Bluetooth 4.0 and USB-A Dongle" },
        { label: "USB Type", value: "USB-A (Standard)" },
        { label: "Wearing Style", value: "Over-the-head" },
        { label: "Microsoft Teams", value: "Certified for Microsoft Teams" },
        { label: "Headset Model", value: "Jabra Evolve 65 SE MS Stereo" },
        { label: "Hearing Aid Compatible (HAC)", value: "Not specified" },
      ],
    },
    {
      id: 2,
      imageSrc: "https://www.headset-store.co.uk/user/products/Plantronics%203220.jpg",
      ProductName: "Plantronics Blackwire c3220 Stereo USB Headset",
      price: "20.50",
      description:
        "The Plantronics Blackwire c3220 Stereo USB Headset is a versatile and durable headset designed for all-day use. It features a noise-cancelling microphone that helps reduce background noise for clear and professional-quality calls. The comfortable and lightweight design makes it ideal for extended wear, and the inline controls allow for easy call management and volume adjustment. Whether you're working from home or in the office, the Plantronics Blackwire c3220 is a reliable choice for all your communication needs.",
      features: [
        "Stereo sound for high-quality audio",
        "Noise-cancelling microphone",
        "Inline controls for call management",
        "Adjustable headband and foam ear cushions",
        "Compatible with PC and Mac",
        "USB-A connection",
      ],
      packageContents: [
        "Plantronics Blackwire c3220 Stereo USB Headset",
        "Carry Pouch",
        "Quick Start Guide",
      ],
      additionalInformation: [
        { label: "Model", value: "21614" },
        { label: "Bar Code", value: "0017229160171" },
        { label: "Part Number", value: "209745-202" },
        { label: "Brand", value: "Plantronics" },
        { label: "Corded or Cordless", value: "Corded" },
        { label: "New or Refurbished?", value: "Brand New" },
        { label: "For Use With", value: "PC and Mac" },
        { label: "Connects Using", value: "USB" },
        { label: "USB Type", value: "USB-A (Standard)" },
        { label: "Wearing Style", value: "Over-the-head" },
        { label: "Microsoft Teams", value: "Not certified for Microsoft Teams" },
        { label: "Headset Model", value: "Plantronics Blackwire c3220" },
        { label: "Hearing Aid Compatible (HAC)", value: "Telecoil Hearing Aid Compatible" },
      ],
    },
    // Add more products for "wireless-pc-headsets" category
  ],
  "usb-pc-headsets": [
    {
      id: 3,
      imageSrc: "https://www.headset-store.co.uk/user/products/large/headsets/EPOS%20Sennheiser/epos_pc8_2023_1.jpg",
      ProductName: "Sennheiser PC 8 USB Headset",
      price: "22.95",
      description:[
      "The Sennheiser PC 8 USB headset is a great value, convenient binaural PC headset for internet-based calls. With simple Plug and Play installation via the USB cable, you can connect it to your computer easily and start chatting and calling on the internet (Skype, VoIPbuster etc...) straight away. This PC 8 headset allows you to enjoy calls hands-free without breaking the bank. Its light and practical binaural style headset lets you focus all your attention on your conversations, isolating external noise"   ]     ,
      features: [
        "Noise cancelling microphone",
        "In-line volume/mute control",
        "Plug and play via USB",
        "Comfortable ear cushions",
        "Excellent voice quality",
        "Adjustable microphone",
        "Perfect for VoIP communications"
      ],
      packageContents: [
        "Jabra Evolve Bluetooth Headset",
        "Carry Pouch",
        "Jabra USB-A Wireless Bluetooth Adapter",
        "USB-A charging cable",
      ],
      additionalInformation: [
        { label: "Model", value: "21020" },
        { label: "Bar Code", value: "4044155076103" },
        { label: "Part Number", value: "504197 / 1000432" },
        { label: "Brand", value: "JSennheiser" },
        { label: "Corded or Cordless", value: "Corded" },
        { label: "New or Refurbished?", value: "Brand New" },
        { label: "For Use With", value: "For PC Only" },
        { label: "Connects Using", value: "USB" },
        { label: "USB Type", value: "USB-A (Standard)" },
        { label: "Wearing Style", value: "Double Ear (Duo)" },
        { label: "Microsoft Teams", value: "Microsoft Teams Compatible" },
        { label: "Headset Model", value: "JSennheiser PC Chat" },
        { label: "Hearing Aid Compatible (HAC)", value: "Not specified" },
      ],
    },
  ],
  // Add products for other categories
};
